### ISSUE TITLE
세션에 userId 추가하기

### ISSUE THREAD

**Issue by hyejj19** [bottle-note/bottle-note-frontend#94]
### 이슈

토큰에서 파싱한 데이터 중 userId 를 추가해보자

### 작업사항

- [ ] 토큰 파싱
- [ ] 토큰 타입에 userId 추가
- [ ] userId 를 포함하도록 수정

### 작업 이유
* userId 가 사용되는 부분이 많아서 세션 데이터에 추가

**Comment by sarumi-k** [comment]
혜정님 이거 지금 session에 들어가 있더라고요! 따로 수정 하신 건가요? 해당 이슈랑 상관없이?

**Comment by hyejj19** [comment]
> 혜정님 이거 지금 session에 들어가 있더라고요! 따로 수정 하신 건가요? 해당 이슈랑 상관없이?

해결됌!
